Support setting robot account secret #156
BESTSELLER/terraform-provider-harbor pull request #157
Opened 2021-12-01 13:05 UTC by wrighbr

2021-12-01 13:48 UTC, Andrei-Predoiu approved these changes

2021-12-02 09:50 UTC, SimonAlling requested changes
Wow, that was fast!

2021-12-02 09:50 UTC, SimonAlling commented on provider/resource_robot_account.go
> +				// Computed:  true,
Commented code?

2021-12-02 15:35 UTC, SimonAlling commented on provider/resource_robot_account.go
> +				// Computed:  true,
Fixed in f98649e.

2021-12-03 06:55 UTC, merged